import { Footer } from "@/components/footer";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
// import "./globals.css";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moustachu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={raleway.variable}>
      <body>{children}</body>
      <Footer />
    </html>
  );
}
